
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Electronics for the Rest of Us!
description: Talha Amjad | INSPIRE 1A03 | Spring, 2020


theme: jekyll-theme-midnight
