
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Talha Amjad's Webpage
description: edit your description in /docs/_config.yml

theme: jekyll-theme-midnight